CREATE DATABASE IF NOT EXISTS Yagra DEFAULT CHARACTER SET = utf8;
USE Yagra;
CREATE TABLE IF NOT EXISTS User (
    username VARCHAR(32) NOT NULL,
    password BINARY(32) NOT NULL,
    salt BINARY(32) NOT NULL,
    PRIMARY KEY USING BTREE (username)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS Auth (
    username VARCHAR(32) NOT NULL,
    token VARCHAR(32) NOT NULL,
    PRIMARY KEY USING BTREE (username)) ENGINE = INNODB;
CREATE TABLE IF NOT EXISTS Image (
    hashcode VARCHAR(32) NOT NULL,
    filename VARCHAR(64) NOT NULL,
    PRIMARY KEY USING HASH (hashcode)) ENGINE = INNODB;

